# Generated by Django 4.1.2 on 2022-10-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('c_first', models.CharField(default='', max_length=1000)),
                ('c_second', models.CharField(default='', max_length=1000)),
                ('c_operator', models.CharField(default='', max_length=4)),
                ('c_result', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
